
version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: vault-telegram-vault_app_1
      APP_PORT: 8080

  app:
    image: pitcentr/telegram-vault:latest
    user: "1000:1000"
    init: true
    restart: unless-stopped
    stop_grace_period: 1m
    environment:
      TG_TOKEN: ${APP_TG_TOKEN}
      PB_URL: http://pocketbase_server:8090
      PB_ADMIN: ${APP_PB_ADMIN}
      PB_PASSWORD: ${APP_PB_PASSWORD}
      MASTER_PASSWORD: ${APP_MASTER_PASSWORD}
      ALLOWED_USERS: ${APP_ALLOWED_USERS}
    depends_on:
      - pocketbase
